// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	DeleteUser(ctx context.Context, uid string) error
	GetUser(ctx context.Context, uid string) (GetUserRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserVerified(ctx context.Context, arg UpdateUserVerifiedParams) error
}

var _ Querier = (*Queries)(nil)
