// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateRecoveryAccount(ctx context.Context, arg CreateRecoveryAccountParams) (RecoverAccount, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserOTP(ctx context.Context, arg CreateUserOTPParams) error
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeleteSessionUser(ctx context.Context, uid string) error
	GetRecoverAccount(ctx context.Context, arg GetRecoverAccountParams) (RecoverAccount, error)
	GetRefreshToken(ctx context.Context, id string) (Session, error)
	GetUserByEmailAndUsername(ctx context.Context, arg GetUserByEmailAndUsernameParams) (User, error)
	GetUserByEmailOrUsername(ctx context.Context, username string) (User, error)
	GetUserByUid(ctx context.Context, uid string) (User, error)
	GetVerifyEmail(ctx context.Context, arg GetVerifyEmailParams) (VerifyEmail, error)
	UpdateRecoverAccount(ctx context.Context, arg UpdateRecoverAccountParams) error
	UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error
	UpdateUserLastLogin(ctx context.Context, uid string) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserVerified(ctx context.Context, arg UpdateUserVerifiedParams) error
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) error
}

var _ Querier = (*Queries)(nil)
